name: StaticDictionary Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./StaticDictionary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Clean Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn -B package
      - name: Run Tests
        run: mvn surefire:test