name: StaticDictionary Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Clean Maven
        run: mvn clean --file StaticDictionary/pom.xml
      - name: Build with Maven
        run: mvn -B package --file StaticDictionary/pom.xml